name: "📦 Build Web-Client Package"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu

          echo "APP_VERSION=$(yq --exit-status '.version' web-client/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' web-client/metaValues.yaml)" >> ${GITHUB_OUTPUT}

  buildRpm:
    needs:
      - gatherFacts
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/jellyfin-rpm-builder:fedora-20221027
    steps:
      - name: "Checkout RPM Repository"
        uses: actions/checkout@v3
        with:
          path: jellyfin-rpm

      - name: "Checkout Code Repository"
        uses: actions/checkout@v3
        with:
          repository: jellyfin-sandbox/jellyfin-web-sandbox
          ref: "${{ needs.gatherFacts.outputs.appGitSha }}"
          path: jellyfin-web

      - name: "Copy fedora Folder"
        run: cp -r jellyfin-rpm/web-client/* jellyfin-web

      - name: "Build RPM"
        run: bash jellyfin-web/buildRpmInContainer.sh

      - name: "Publish Validation Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: jellyfin-web
          path: out
          if-no-files-found: error

  publishDeb:
    needs:
      - gatherFacts
      - buildRpm
    if: ${{ ! contains(needs.gatherFacts.outputs.appVersion, 'unstable') }}
    runs-on: ubuntu-22.04
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3

      - name: "Debug"
        run: ls -la
