name: "📦 Build Server Package"

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu

          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}

  fedora:
    needs:
      - gatherFacts
    uses: ./.github/workflows/_meta-rpmBuild.yaml
    with:
      buildOs: fedora
      buildImageTag: fedora-20221027
      rpmSpec: server
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}

  rockyLinux:
    needs:
      - gatherFacts
    uses: ./.github/workflows/_meta-rpmBuild.yaml
    with:
      buildOs: rockylinux
      buildImageTag: rockylinux-20221027
      rpmSpec: server
      repository: ${{ needs.gatherFacts.outputs.appRepo }}
      repositoryRef: ${{ needs.gatherFacts.outputs.appGitSha }}

  publishRpm:
    needs:
      - gatherFacts
      - fedora
      - rockyLinux
    if: ${{ ! contains(needs.gatherFacts.outputs.appVersion, 'unstable') }}
    runs-on: ubuntu-22.04
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: server-rpm

      - name: "Debug"
        run: ls -la
