name: "📦 Build Server Package"

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  gatherFacts:
    runs-on: ubuntu-22.04
    outputs:
      appRepo: ${{ steps.variables.outputs.APP_REPO }}
      appGitSha: ${{ steps.variables.outputs.APP_GIT_SHA }}
      appVersion: ${{ steps.variables.outputs.APP_VERSION }}
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Gather Variables"
        id: variables
        run: |-
          set -exu

          echo "APP_REPO=$(yq --exit-status '.repository' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_VERSION=$(yq --exit-status '.version' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}
          echo "APP_GIT_SHA=$(yq --exit-status '.git_sha' server/metaValues.yaml)" >> ${GITHUB_OUTPUT}

  buildRpm:
    needs:
      - gatherFacts
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/${{ github.repository_owner }}/jellyfin-rpm-builder:fedora-20221027
    steps:
      - name: "Checkout RPM Repository"
        uses: actions/checkout@v3
        with:
          path: jellyfin-rpm

      - name: "Checkout Code Repository"
        uses: actions/checkout@v3
        with:
          repository: ${{ needs.gatherFacts.outputs.appRepo }}
          ref: ${{ needs.gatherFacts.outputs.appGitSha }}
          path: jellyfin-code

      - name: "Copy fedora Folder"
        run: cp -r jellyfin-rpm/server/* jellyfin-code

      - name: "Build RPM"
        run: bash jellyfin-code/buildRpmInContainer.sh

      - name: "Publish Validation Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: server-rpm
          path: out
          if-no-files-found: error

  publishRpm:
    needs:
      - gatherFacts
      - buildRpm
    if: ${{ ! contains(needs.gatherFacts.outputs.appVersion, 'unstable') }}
    runs-on: ubuntu-22.04
    steps:
      - name: "Download Artifacts"
        uses: actions/download-artifact@v3
        with:
          name: server-rpm

      - name: "Debug"
        run: ls -la
